### ISSUE TITLE
How do you use this with logsearch-boshrelease?

### ISSUE THREAD

**Issue by devcamcar** [logsearch/logsearch-filters-cf#13]
With https://github.com/logsearch/logsearch-filters-cf/issues/11 applied, I've got this building and outputting the cloudfoundry.conf file, but it's unclear how I am supposed to add this to the bosh release to deploy the Cloud Foundry configuration.  I'm sure it's simple but I'm fairly new to Logsearch.  Thanks!

**Comment by tyyko** [comment]
I think that you can just move it to logsearch-boshrelease/examples/filters.conf and then deploy logsearch with a template like https://github.com/logsearch/logsearch-boshrelease/blob/develop/examples/bosh-lite.yml that will search for that file.

Meanwhile that filters will not work with the last CF release, they are working on a new version of these filters

@mrdavidlaing I have a match pattern for grok that seems to work on the grok web debugger(tested with some logs from a simple php app on CF bosh-lite) but not when I deploy it on the bosh release, hoping it could be useful for someone I'll post it here

```
%{NUMBER:message_lenght} %{SYSLOG5424PRI}%{NONNEGINT:syslog5424_version} %{TIMESTAMP_ISO8601:syslog5424_ts} %{WORD:LogSource} (?<sourceId>[^ ]*) (?<betweenBrackets>(\[[^ \]]*\])) - - %{IPORHOST:HostSource} -( -)? \[(%{HTTPDATE:EventTimestamp}|(?<EventTimestamp>%{MONTHDAY}/%{MONTHNUM}/%{YEAR}:%{TIME} %{INT}))\] \"%{WORD:method} %{URIPATHPARAM:path} (?<protocol>[^\"]*)"(?<STRANGE_NUM>[^\"]*)\"-\" \"(?<agent>[^\"]*)\"(?<AnythingElse>.*)
```

**Comment by mrdavidlaing** [comment]
@devcamcar We're working with https://github.com/cloudfoundry-community/logsearch-boshworkspace to get logsearch working with the latest version of CF.  Please track that repo.
